version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: start local
          command: echo starting in local
      - run:
          name: test local
          command: echo test in local
  acceptance_test:
    steps:
      - run:
          name: start rec
          command: echo push to heroku rec
      - run:
          name: test rec
          command: echo test rec
  deploy:
    steps:
      - run:
          name: start prod
          command: echo push to heroku prod
      - run:
          name: test prod
          command: echo test prod

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - acceptance_test:
          requires:
            - build
      - deploy:
          requires:
            - acceptance_test
