version: 2
jobs:
  build:
    working_directory: ~/clickclack-web
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && git clone --branch "master" --depth 50 git@github.com:thorium-e2e/clickclack-web.git ~/clickclack-web
      - run: git push https://heroku:3a12d835-fb52-4977-946b-7a0c30a0bad5@git.heroku.com/rec-clickclack-web.git master
  accept:
    working_directory: ~/clickclack-web-tests
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && git clone --branch "master" --depth 50 git@github.com:thorium-e2e/clickclack-web-tests.git ~/clickclack-web-tests
      - run: mvn test

  deploy:
    working_directory: ~/clickclack-web
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
      - run: git push https://heroku:3a12d835-fb52-4977-946b-7a0c30a0bad5@git.heroku.com/clickclack-web.git master


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - accept:
          requires:
            - build
      - deploy:
          requires:
            - accept
