version: 2
jobs:
  build:
    working_directory: ~/clickclack-web
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
      - clone project from github
      - run:
          name: clone command
          command: git clone --branch "master" --depth 50 git@github.com:thorium-e2e/clickclack-web.git ~/clickclack-web
      - push project to heroku qa
      - run:
          name: push qa command
          command: git push https://heroku:3a12d835-fb52-4977-946b-7a0c30a0bad5@git.heroku.com/rec-clickclack-web.git master
  accept:
    working_directory: ~/clickclack-web-tests
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
      - clone project from github
      - run:
          name: clone command
          command: git clone --branch "master" --depth 50 git@github.com:thorium-e2e/clickclack-web-tests.git ~/clickclack-web-tests
      - run tests with maven
      - run:
          name: mvn test
          command: mvn test

  deploy:
    working_directory: ~/clickclack-web
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers-legacy
    steps:
      - push project to heroku qa
      - run:
          name: push qa command
          command: git push https://heroku:3a12d835-fb52-4977-946b-7a0c30a0bad5@git.heroku.com/clickclack-web.git master


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - accept:
          requires:
            - build
      - deploy:
          requires:
            - accept
